server:
  port: 8081
#  servlet:
#    context-path: /api

springdoc:
  swagger-ui:
#    path: /api-docs.html
    tags-sorter: alpha # 컨트롤러의 @Tag() 이름 알파벳 순
    operations-sorter: method # http method 순서

spring:
  application:
    name: admin-test
  profiles:
    include:
      - secret
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none # create, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
